### ISSUE TITLE
Problem loading classifier first time

### ISSUE THREAD

**Issue by jbeuckm** [NaturalNode/natural#241]
I am having a problem in OSX / node v0.12.3

This example crashes if no classifier file exists:

``` javascript
var natural = require('natural');

natural.BayesClassifier.load("./listing_title_classifier.json", null, function (err, loaded_classifier) {
        if (err) {
            console.log("no classifier found - starting new...");
        } else {
            console.log("loaded classifier");
        }
    });
```

And here is the console output:

```
no classifier found - starting new...
/Users/joebeuckman/Documents/get_money/node_modules/natural/lib/natural/classifiers/classifier.js:125
    classifier.stemmer = stemmer || PorterStemmer;
                       ^
TypeError: Cannot set property 'stemmer' of undefined
    at Function.restore (/Users/joebeuckman/Documents/get_money/node_modules/natural/lib/natural/classifiers/classifier.js:125:24)
    at restore (/Users/joebeuckman/Documents/get_money/node_modules/natural/lib/natural/classifiers/bayes_classifier.js:39:29)
    at /Users/joebeuckman/Documents/get_money/node_modules/natural/lib/natural/classifiers/bayes_classifier.js:51:23
    at /Users/joebeuckman/Documents/get_money/node_modules/natural/lib/natural/classifiers/classifier.js:152:13
    at fs.js:263:20
    at FSReqWrap.oncomplete (fs.js:95:15)
```

**Comment by TheDailySpank** [comment]
To get around this I test for the existence of the training json file. This is a code snippet from my sentiment training script.

```javascript
function train(text, classification) {
	if (fs.exists('sentiment.json')) {
		natural.BayesClassifier.load('sentiment.json', null, function(err, classifier) {
			classifier.addDocument(text, classification);
			classifier.train();
			classifier.save('sentiment.json', function(err, classifier) {});
		});
	} else {
		classifier.addDocument(text, classification);
		classifier.train();
		classifier.save('sentiment.json', function(err, classifier) {});
	}
}
```

**Comment by decoderling** [comment]
I just tested this on OSX and am not seeing the issue. It's possible this was due to an older version of node or some other factor.

_node version_
```
➜  natural node --version
v7.5.0
```

_test file_
```
➜  natural cat index.js 
var natural = require('natural');

natural.BayesClassifier.load('./listing_title_classifier.json', null, function(err, loaded) {
    if (err) {
        console.log('no classifier found - starting new...');
    } else {
        console.log('loaded classifier');
    }
});
```

_results ran_
```
➜  natural node index.js 
no classifier found - starting new...
```

It might be useful to add a functional test around this or just choose to do extra checks in the code.
