### ISSUE TITLE
TypeError: _.assign is not a function

### ISSUE THREAD

**Issue by amragaey** [NaturalNode/natural#407]
While using Approximate String Matching function, I got this error.

`TypeError: _.assign is not a function
    at Object.LevenshteinDistance (/Users/amragaey/Desktop/mo4_botit/botit_bot/node_modules/natural/lib/natural/distance/levenshtein_distance.js:101:24)
    at Object.<anonymous> (/Users/amragaey/Desktop/mo4_botit/botit_bot/items/known.js:6:9)
    at Module._compile (module.js:609:14)
    at Object.Module._extensions..js (module.js:623:10)
    at Module.load (module.js:531:32)`

The problem is that _Undersocre_ no more support 'assign' function. It's replaced now with [_.extend()](http://underscorejs.org/#extend). the functionality of extension is also natively support in ES6 as [Object.assign()](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/assign)

**Comment by Hugo-ter-Doest** [comment]
Merged #408.
