### ISSUE TITLE
Not compatible with electron?

### ISSUE THREAD

**Issue by lagartoverde** [NaturalNode/natural#412]
Hi, I get this error using the library, I'm trying to use the natural Porter stemmer and the sentence tokeniser and in both of them I get the same error

```
Uncaught Error: ENOENT: no such file or directory, open '//../../../../data/kata-dasar.txt'
    at Object.fs.openSync (fs.js:652:18)
    at Object.module.(anonymous function) [as openSync] (ELECTRON_ASAR.js:172:20)
    at Object.fs.readFileSync (fs.js:553:33)
    at Object.fs.readFileSync (ELECTRON_ASAR.js:508:29)
```

Thank you.

**Comment by Hugo-ter-Doest** [comment]
Are you using the Indonesian stemmer? It seems so because it needs `kata-dasar.txt`. Could you elaborate a bit more about what you did? And how you required the stemmer? Some code would help to solve this.

Hugo

**Comment by wandonye** [comment]
I can confirm this error with either
```
import {SentenceAnalyzer, PorterStemmer} from 'natural';
const analyzer = new SentenceAnalyzer("English", PorterStemmer, "afinn");
```
or the same codes as in README.md
