### ISSUE TITLE
DeprecationWarning: Calling an asynchronous function without callback is deprecated.

### ISSUE THREAD

**Issue by dipockdas** [NaturalNode/natural#432]
While testing synonyms, I get the following error:

````
(node:94222) [DEP0013] DeprecationWarning: Calling an asynchronous function without callback is deprecated.
    at makeCallback (fs.js:145:12)
    at Object.fs.close (fs.js:628:20)
    at /Users/----/node_modules/natural/lib/natural/wordnet/wordnet_file.js:58:38
    at /Users/----/node_modules/natural/lib/natural/wordnet/data_file.js:32:7
    at /Users/----/node_modules/natural/lib/natural/wordnet/wordnet_file.js:40:9
    at FSReqWrap.wrapper [as oncomplete] (fs.js:680:17)
````

This is the link in wordnet_file,js that seems to be the problem

````
callback(err, fd, function() {fs.close(fd)});
````

Passing a callback is now mandatory when using fs.close. Ref: https://nodejs.org/api/fs.html#fs_fs_close_fd_callback

I was able to address the issue by adding an error handler in the call:

````
    callback(err, fd, function() {
       fs.close(fd, 
        (e) => { /* error handler */  
           if (typeof e !== null && typeof data !== "undefined") {
             console.log(`Error ${e.name} ${e.message}`);
           } 
        })});
````

**Comment by Hugo-ter-Doest** [comment]
I think you are using the version from NPM because in the Github version there is already a callback in place:

```javascript
    callback(err, fd, function() {
      fs.close(fd, function(error) {
        if (error) {
          throw error;
        }
      })
    });
```
It's better to use the Github version at the moment.

Hugo
