### ISSUE TITLE
Sentiment Analyzer is failing when it is instantiated

### ISSUE THREAD

**Issue by luismr** [NaturalNode/natural#636]
Hello folks, sorry to bug you but it is driving me mad. I am trying to use the SentimentAnalyzer and it is failing and I have no Idea what to do.

```
import { WordTokenizer, SentenceTokenizer, SentimentAnalyzer, PorterStemmer } from 'natural'

function getSentiment (words: string [], language: string): number {
  const stemmer = PorterStemmer
  const analyzer = new SentimentAnalyzer(language, stemmer, 'affin')
  return analyzer.getSentiment(words)
}

Console.log(getSentiment(['hello', 'world'], 'English'))
```

It is throwing this error

```
2022-01-28T15:49:12.135Z	834a7e3e-aa1a-42fc-a5e4-8fb6af050239	INFO	TypeError: Cannot read property 'English' of undefined
    at new SentimentAnalyzer2 (/var/task/index.js:745461:64)
    at getSentiment (/var/task/index.js:786269:20)
    at naturalLanguageAnalysis (/var/task/index.js:786251:24)
    at Runtime.handler (/var/task/index.js:786303:22)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
```

I already tried in Javascript and Typescript notations

My package.json

```
"dependencies": {
    "@types/natural": "^5.1.0",
    "natural": "^5.1.13",
  },
```

Any idea?

**Comment by Hugo-ter-Doest** [comment]
You misspelled the vocabulary type as 'affin'. This should be 'afinn'.

**Comment by luismr** [comment]
Bloody Hell 🤯

Can I suggest create a Constant or ENUM to avoid it?
