### ISSUE TITLE
Dynamic require of "util" is not supported

### ISSUE THREAD

**Issue by ralyodio** [NaturalNode/natural#654]
I'm getting this error using `adapter-node` with sveltekit after upgrading to latest.

`Dynamic require of "util" is not supported`

Here's the node error:

```

$ node build/index.js 
Listening on 0.0.0.0:3000
Error: Dynamic require of "util" is not supported
    at file:///home/ettinger/www/grazily.com/grazily-ui/build/server/chunk-BHN6OJC3.js:12:9
    at node_modules/natural/lib/natural/tokenizers/aggressive_tokenizer.js (file:///home/ettinger/www/grazily.com/grazily-ui/build/server/chunk-METZWSI6.js:239:16)
    at __require2 (file:///home/ettinger/www/grazily.com/grazily-ui/build/server/chunk-BHN6OJC3.js:15:50)
    at node_modules/natural/lib/natural/phonetics/phonetic.js (file:///home/ettinger/www/grazily.com/grazily-ui/build/server/chunk-METZWSI6.js:255:21)
    at __require2 (file:///home/ettinger/www/grazily.com/grazily-ui/build/server/chunk-BHN6OJC3.js:15:50)
    at node_modules/natural/lib/natural/phonetics/soundex.js (file:///home/ettinger/www/grazily.com/grazily-ui/build/server/chunk-METZWSI6.js:285:20)
    at __require2 (file:///home/ettinger/www/grazily.com/grazily-ui/build/server/chunk-BHN6OJC3.js:15:50)
    at node_modules/natural/lib/natural/index.js (file:///home/ettinger/www/grazily.com/grazily-ui/build/server/chunk-METZWSI6.js:12623:23)
    at __require2 (file:///home/ettinger/www/grazily.com/grazily-ui/build/server/chunk-BHN6OJC3.js:15:50)
    at node_modules/in-a-nutshell/lib/in-a-nutshell.js (file:///home/ettinger/www/grazily.com/grazily-ui/build/server/chunk-METZWSI6.js:12683:19)
```

**Comment by SachaG** [comment]
Same here.

**Comment by Hugo-ter-Doest** [comment]
I checked the source files that are mentioned in your stack trace. But I don't see a dynamic require of `util`. Any clue what is going on?

**Comment by mkappelhof** [comment]
I have the exact same issue as @adaboese has when using in a Remix app, but the same code works fine when running outside of Remix directly on Node.js so it could very well be an issue with Remix

**Comment by Hugo-ter-Doest** [comment]
Oke, let's have a look.

Webworker threads are not dynamically required, a try-catch construct is used:
```
try {
  Threads = require('webworker-threads')
} catch (e) {
  // Since webworker-threads are optional, only thow if the module is found
  if (e.code !== 'MODULE_NOT_FOUND') throw e
}
```
So it is always tried to load the module.
